### ISSUE TITLE
Error running shader on boot

### ISSUE THREAD

**Issue by wraybowling** [patriciogonzalezvivo/glslViewer#100]
I tried making glslViewer run on boot so it could be part of an installation. So I added this to my .bashrc

```
# start video synth
glslViewer ~/Villarossa/vengance.frag -w 640 -h 480
```
I tried a couple of different methods, local.rc and .bashrc  Using .bashrc seemed like the better option since local.rc will complain if there is any text output of any kind. But I just get this error, regardless of the permissions set on the application or the shader file.

```
Error watching file /home/Villarossa/vengance.frag
Usage: glslViewer shader.frag [shader.vert] [mesh.(obj/.ply)] [texture.(png/jpg)] [-textureNameA texture.(png/jpg)] [-u] [-x x] [-y y] [-w width] [-h height] [-l/--livecoding] [--square] [-s seconds] [-o screenshot.png]
```

Note: this is on Raspbian GNU/Linux 8 on a Pi 2

**Comment by patriciogonzalezvivo** [comment]
Hi! Thanks for the patience

Seams is taking `/home` as the Home folder instead of `/home/pi` or what ever user home folder you are using. Maybe you are running that line on the .bashrc script to soon on the script. Have you tried using the absolute path? 

In any case this seams more of a problem of Linux permissions and file system rather than a glslViewer.

All the best,

Patricio

**Comment by wraybowling** [comment]
I wonder if a flag to disable file watching would remedy the problem too. Another thing I'm thinking of trying is changing the executable permissions on the .frag file. The permissions are kind of daisy-chained, yeah?

**Comment by patriciogonzalezvivo** [comment]
I don't think is the file watcher. Seams to be something at the OS/FS level.

Did you notices is searching for it in: `/home/Villarossa/vengance.frag` instead of `/home/pi/Villarossa/vengance.frag` (which will be the destination of `glslViewer ~/Villarossa/vengance.frag -w 640 -h 480` if your user is `pi`).

I'm not sure this script is run by `pi` you should put it in a common directory where all users have access... including the `system`.

But again, this doesn't seams like a glslViewer issue. Is about your linux distribution and the FS permissions.

**Comment by wraybowling** [comment]
For anyone out there who may find this and wonder what the solution was:

1. Putting the shader files in a new directory like /usr/local/shaders. Raspbian likes to complain every step of the way that you're doing something horrible, but it's okay. Use sudo to force the creation of folders and files.
2. Set up an [init.d script](http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html) that runs something like /usr/local/bin/glslViewer /usr/local/shaders/myShader.frag
