### ISSUE TITLE
Render shader to an image sequence

### ISSUE THREAD

**Issue by NightMachinary** [patriciogonzalezvivo/glslViewer#106]
I want to render the video a shader generates to an image sequence. Can I do that? If not, can you add this feature? Or possibly hint me at another tool. :)

**Comment by patriciogonzalezvivo** [comment]
Hi! 

Adding video decoding support on GlslViewer exceed the goals of the project. But can be done easily using GlslViewer together with FFmpeg. Because GlslViewer can be lunch headless from the command line, it's very easy to create a script (bash, python, etc) that:

1. Transform a video file in a image secuence. Ex:
```bash
ffmpeg -i input.mov -r 0.25 output_%04d.png
```

2. Then running a shader in GlslViewer taking as an input each one of the images generated and setting as out put another image. For that is important to set both the -o parameter and -s so glslViewer can be exit after S seconds Ex:

```bash
for i in *.png;do glslViewer shader.frag --u_tex0 "$i" -s 1 -o "$i_final.png";done
```
 
Using FFmpeg it's also possible to add back all images into a video

**Comment by NightMachinary** [comment]
No, I want to have the output of glslViewer as an image sequence; I.e., I
want to render my shader to an image sequence.

**Comment by patriciogonzalezvivo** [comment]
Got it. I just add new command for the console in:

```
// > sequence,0,1
```

This for example will record a sequence of images at 30fps, from second 0 to second 1
Here I made a little video of how it works https://youtu.be/7gTTKAQN4Hk 

Please share and tell me how it went

**Comment by NightMachinary** [comment]
@patriciogonzalezvivo Thanks! It seems to work properly. 👍🏻

**Comment by NightMachinary** [comment]
@patriciogonzalezvivo It'd be nice to make the fps settable as well: sequence,fps,s0,s1

**Comment by NightMachinary** [comment]
It’s better to be able to set it manually. One might want to try different
FPSs.

**Comment by blinry** [comment]
I also would like to be able to specify the frame rate! 30 fps is not sufficient for some animations involving fast movement. Should we re-open this, or make a new issue?

**Comment by patriciogonzalezvivo** [comment]
Done, please give it a shot https://github.com/patriciogonzalezvivo/glslViewer/commit/f2f1f6189f9411a7fb0b654f65f4199d7e427ee2

**Comment by blinry** [comment]
Perfect, thanks a million!
