### ISSUE TITLE
[BUG?] using auto save does bring a major hanging to changing the shader

### ISSUE THREAD

**Issue by lewislepton** [patriciogonzalezvivo/glslViewer#124]
this is something ive ran into when making my tutorial series.

I use auto save, set to about 300ms - but with pretty much a lot of the code ive been doing, which is really simple right now. it hangs terribly, sometimes not even changing the shader at all to the newest values set to something such as the radius.

luckily editing is on my side, but its just something id like to bring up since its something that could be looked into

thanks though for this tool, its awesome ;)

**Comment by patriciogonzalezvivo** [comment]
Hi! This is an interesting case. The auto-reload use the timestamp of the file system to check for when was the last time some of the files was saved, when it detects a change on the file stamp it reloads the shader and recompile it with out checking that there is actual changes on the text. This recompilation  halts the system for a while. Everything stops until the re compilation is over, the geometry and texture are linked to the new program.

I could add an extra check to prevent the entire shader to be recompile if there is no actual changes. Seams like a reasonable thing to do. Still will be a good idea to debounce the autosave to the moment you finish editing to prevent errors and reduce the number of compilations per second.

**Comment by patriciogonzalezvivo** [comment]
That said, I recommend using glslEditor or http://editor.thebookofshaders.com/ to realtime editing... beside the debounced recompilation on changes... i had add it a lot of pickers for colors, vec3, vec2 and floats. Together with a couple of extra goodies. You can run it natively as an electron app (https://github.com/patriciogonzalezvivo/glslEditor). Because it use glslCanvas all the the uniforms are conveniently the same that glslViewer and ofxShader (https://github.com/patriciogonzalezvivo/ofxShader).

**Comment by patriciogonzalezvivo** [comment]
Any develop in this one?
