### ISSUE TITLE
Resolving #include dependency paths correctly on Windows

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [patriciogonzalezvivo/glslViewer#232]
A couple of nice friends had tried use [LYGIA](https://github.com/patriciogonzalezvivo/lygia) in windows and find out that the paths are not getting resolve correctly because Windows incompatible folder structure with POSIX style. This will require some extra wiring [here](https://github.com/patriciogonzalezvivo/glslViewer/blob/main/src/io/fs.cpp#L66-L82) to basically support POSIX on windows.

**Comment by totalgee** [comment]
This is odd because most C++ library functions I've used on Windows work fine with forward or backward slash as path separators. However, just looking at the code quickly, this function seems very wrong/dangerous:

https://github.com/patriciogonzalezvivo/glslViewer/blob/main/src/io/fs.cpp#L57-L64

You definitely shouldn't be calling `free()` on the C string held by the `std::string` named `_path`! This is quite likely where it's crashing...

I don't have time to look in more detail now, but that definitely looks bad... (-;

BTW, have you thought about using `std::filesystem` to manage paths? It's a bit better for cross-platform work, as long as you can count on modern enough compilers (C++17).
