### ISSUE TITLE
Segmentation fault on opening any .frag - MacOS Catalina on 2014 MBP

### ISSUE THREAD

**Issue by chrispetrone** [patriciogonzalezvivo/glslViewer#270]
Every time I open a .frag, the viewer opens and briefly displays the .frag file, and then immediately crashes and seg faults.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/19274822/170742508-b68a8f83-27c6-4d6e-af0b-c972bb37c730.png">

I have tried removing glslViewer and compiling it from source, redownloading ffmpeg, glfw, and other dependencies.  I cant seem to get any information about the error apart from the seg faults when I open .frags.

When I run glslViewer alone, I get this:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/19274822/170742753-a714598f-f302-4ce5-84d8-9c0c668ec13c.png">

https://user-images.githubusercontent.com/19274822/170743376-53595f1f-9afe-4c86-81bb-bcef9ea00630.mov

Could this be because I am on Catalina or running older Intel architecture?

**Comment by patriciogonzalezvivo** [comment]
oh that sound terrible. Do you mind:

1. `git pull` to the latest version. Make sure `deps/ada` submodule is also in the latest `main` branch 
2. removing the build folder entirely
3. commenting this lines https://github.com/patriciogonzalezvivo/glslViewer/blob/main/CMakeLists.txt#L97-L101 
4. re make the build folder, `cd` into it,  run `cmake..` and then `make` as is described here https://github.com/patriciogonzalezvivo/glslViewer/wiki/Compile-on-MacOS#3-compile ??

Apparently the new integration is keeping you out of seeing the prompts. By commenting those lines it shouldn' t compile support for it. 

The plan is to gather more data without ncurses. In the case that fix it... try uncommenting the same lines. and repeat removing and creating the build folder. And see if the problem is coming from ncurses.

I don't think is because of the OS or architecture of your computer. Sorry for all this troubles

**Comment by sejinpark12** [comment]
I had the same issue. It works fine now thanks to your help

**Comment by chrispetrone** [comment]
That fixed it! Thank you @patriciogonzalezvivo 🙏

**Comment by chrispetrone** [comment]
For future reference, commenting out the lines mentioned in [3] solved the issue, and uncommenting them led to the segmentation fault error happening again.
