### ISSUE TITLE
Headless instance does not output image

### ISSUE THREAD

**Issue by DarienBrito** [patriciogonzalezvivo/glslViewer#63]
Hello there,

I've been learning a lot with "The Book of Shaders" and have been using glslViewer to code, thanks so much for publishing them!

One thing I've wanted to do is to export an image from glslViewer. Reading the documentation i see there's a method to do this by creating a PNG image from a headless instance of the viewer, however when I attempt to do:

glslViewer myShader.frag --headless -s 1 -o Myname.png 

I get this message in the console: "Will save screenshot to Myname.png on exit."  and after exiting the instance I get no image at all in the current directory. Is this file being exported to another specific directory or is this a bug?

Thanks a lot!
Darien

**Comment by patriciogonzalezvivo** [comment]
Hi! that's weird, I have been using it in a very similar way for to render the PixelSpiritDeck.com ... are you using the last version? on what OS?

**Comment by doug-moen** [comment]
It works for me. I'm using Ubuntu 16.04 and the latest version of
glslViewer. The file appears in the current directory.

If I don't have write permission in the current directory, then no file is
written, but there is no error message either.

I looked at the source. If stbi_write_png() fails, no file is created and
it returns 0, otherwise it returns 1. It would be good to check if the
return code is 0 and print an error message, but we don't do this. This is
a change that could be made to Texture::savePixels().

**Comment by doug-moen** [comment]
PR #64 contains the suggested change. I tested the change.

**Comment by patriciogonzalezvivo** [comment]
Thanks! great synergy you guys : )

**Comment by DarienBrito** [comment]
Awesome, thank you, I have changed permissions and re-installed glslViewer with the updated code. It works fine now! 

I got the PixelSpiritDeck some days ago btw, looking forward to receive it!
