### ISSUE TITLE
preprocessor error: #version must appear on the first line

### ISSUE THREAD

**Issue by davydka** [patriciogonzalezvivo/glslViewer#67]
I'm receiving the following error when trying to include a version preprocessing line in my fragment shader.
`0:1(1): preprocessor error: #version must appear on the first line`
If i comment out the version, `//#version 100` everything works fine. I can leave the version line in the online editor here:
http://thebookofshaders.com/edit.php?log=170427231821

```
#version 100
#ifdef GL_ES
precision mediump float;
#endif

void main()
{
	// gl_FragCoord contains the window relative coordinate for the fragment.
	// we use gl_FragCoord.x position to control the red color value.
	// we use gl_FragCoord.y position to control the green color value.
	// please note that all r, g, b, a values are between 0 and 1.

	float windowWidth = 1024.0;
	float windowHeight = 768.0;

	float r = gl_FragCoord.x / windowWidth;
	float g = gl_FragCoord.y / windowHeight;
	float b = 1.0;
	float a = 1.0;
	gl_FragColor = vec4(r, g, b, a);
}
```

**Comment by doug-moen** [comment]
We don't currently support #version in glslViewer.

That's a bug. It's caused by the fact that we automatically add text to the beginning of the shader program: the text will be added before the `#version` line. Since `#version` must be the first line, you get an error from the GLSL compiler.

The fix is a change to src/gl/shader.cpp, in Shader::compileShader(). Check if the first line of `_src` is a `#version` line. If so, then add that line to the beginning of `prolog`, and remove or skip over the first line of `_src`.

**Comment by patriciogonzalezvivo** [comment]
@davydka I believe @doug-moen replay to your question... right?
